// ==UserScript==
// @ScriptName        番茄小说[自用]
// @Author            @zqzess
// @UpdateTime        2026-04-11
// @Attention         如果广告仍然存在，请清除缓存或卸载应用重新安装
// @Function          去广告配置（自用，不定期更新）
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.1
// ==/UserScript==


hostname = *.pangolin-sdk-toutiao,*.pangolin-sdk-toutiao.*,*.pstatp.com,*.pstatp.com.*,*.pglstatp-toutiao.com.*,*.pglstatp-toutiao.com,gurd.snssdk.com,gurd.snssdk.com.*,*default.ixigua.com
^https?:\/\/.+\.pangolin-sdk-toutiao\.com\/api\/ad\/union\/sdk\/(get_ads|stats|settings)\/ url reject