// ==UserScript==
// @ScriptName        一些网页[自用]
// @Author            @Gjf-fff
// @UpdateTime        2026-04-13
// @Attention         如果广告仍然存在，请清除缓存或卸载应用重新安装
// @Function          去广告配置（自用，不定期更新）
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.1
// ==/UserScript==


hostname = 18comic.vip,18comic.org
^https?:\/\/18comic\.vip.* url script-response-body https://github.com/Gjf-fff/RejectAD/blob/main/Tool/QuanX/JS/jinman1.js
^https?:\/\/18comic\.org\/.* url script-response-body https://github.com/Gjf-fff/RejectAD/blob/main/Tool/QuanX/JS/jinman1.js
